[project]
name = "df2html"
version = "0.1.0"
description = "Save your pd.DataFrame to .html file with styles of Jupyter Notebook"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["pandas>=2.0.0",]
